name: Postman API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        working-directory: quiz-app/quiz-api
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node dependencies (Newman en local)
        working-directory: quiz-app/quiz-ui
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Start Flask API
        working-directory: quiz-app/quiz-api
        run: |
          python app.py &
          sleep 10

      - name: Run Postman tests with Newman
        working-directory: quiz-app/quiz-ui
        env:
          BASE_URL: "http://127.0.0.1:5000"
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          npx newman run "tests/test_postman_collection.json" \
            --env-var "baseUrl=$BASE_URL" \
            --env-var "pwd=$ADMIN_PASSWORD"
  build-docker:
    runs-on: ubuntu-latest
    needs: test-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: |
          docker build \
            -t quiz-api:ci \
            -f quiz-app/quiz-api/Dockerfile \
            quiz-app/quiz-api

      - name: Build frontend image
        run: |
          docker build \
            -t quiz-ui:ci \
            -f quiz-app/quiz-ui/Dockerfile \
            quiz-app/quiz-ui
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: quiz-app/quiz-api
          file: quiz-app/quiz-api/Dockerfile
          push: true
          tags: nassimm/quiz-api:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: quiz-app/quiz-ui
          file: quiz-app/quiz-ui/Dockerfile
          push: true
          tags: nassimm/quiz-ui:latest


